services:
  - type: web
    name: wally-widgets
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      npm install
      APP_ENV=production npm run build
    startCommand: |
      php artisan migrate --seed
      php artisan serve --host 0.0.0.0 --port 10000
    publishDirectory: ./public/build
    envVars:
      APP_NAME: wally-widgets
      APP_ENV: production
      APP_KEY: base64:ZZbz41MwJUDeVHI64k86dsTDpmBtjXpSBc/DqPmk8lE=
      APP_DEBUG: 'true'
      APP_URL: https://wally-widgets.onrender.com  # Change to your Render URL
      routes:
        - type: web
          source: /
      DB_CONNECTION: mysql
      DB_HOST: your_db_host  # Update this to your actual DB host
      DB_PORT: 3306
      DB_DATABASE: wally_widgets
      DB_USERNAME: wally_widgets # Update to your actual DB username
      DB_PASSWORD: hop!hop!123L  # Update to your actual DB password
    autoDeploy: true
