services:
  - type: web
    name: wally-widgets
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      npm install
      npm run build
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    publishDirectory: ./dist
    envVars:
      APP_NAME: wally-widgets
      APP_ENV: production
      APP_KEY: base64:ZZbz41MwJUDeVHI64k86dsTDpmBtjXpSBc/DqPmk8lE=
      APP_DEBUG: 'false'
      APP_URL: https://wally-widgets.onrender.com  # Change to your Render URL

      LOG_CHANNEL: stack
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug

      DB_CONNECTION: mysql
      DB_HOST: your_db_host  # Update this to your actual DB host
      DB_PORT: 3306
      DB_DATABASE: wally_widgets
      DB_USERNAME: wally_widgets # Update to your actual DB username
      DB_PASSWORD: hop!hop!123L  # Update to your actual DB password

      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

      MEMCACHED_HOST: your_memcached_host  # Update if using Memcached

      REDIS_HOST: your_redis_host  # Update if using Redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      MAIL_MAILER: smtp
      MAIL_HOST: mailpit  # Update if necessary
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"

      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET:
      AWS_USE_PATH_STYLE_ENDPOINT: false

      PUSHER_APP_ID:
      PUSHER_APP_KEY:
      PUSHER_APP_SECRET:
      PUSHER_HOST:
      PUSHER_PORT: 443
      PUSHER_SCHEME: https
      PUSHER_APP_CLUSTER: mt1

      VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
      VITE_PUSHER_HOST: "${PUSHER_HOST}"
      VITE_PUSHER_PORT: "${PUSHER_PORT}"
      VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
      VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
    autoDeploy: true
